# Site settings
title: Generator wpautomate | wordpress cli, wp cli, gulp environment
description: "A better workflow with gulp wp-cli"
url: "https://itobuztech.github.io/generator-wpautomate"
author:
  name: "Prosenjit Manna"
  email: "developer.prosenjit@gmail.com"

# Build settings
baseurl: /generator-wpautomate # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
